### ISSUE TITLE
metadata presentation

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-components-gallery#8] opened 2016-05-03 06:02 UTC
This relates to issue #7:

Some metadata has an identifier, like "tags". Other do not, like "accessibility statement". They are also links, which makes them look differently. It is difficult to scan and parse the information (especially when they are inline as outlined in issue #7).

You could reword to make it a full list that is easy to scan:
- Tags: x, y, z
- License: MIT license
- Information last updated: 2016-04-28
- Accessibility: Statement provided
- Repository: source code available (Github Statistics:  187 Stars,  485 Forks, Last Update: 2016-05-02)

This makes it longer but easier to process IMO. Not high priority and can wait till later versions.

**Comment by yatil** [comment] 2016-05-05 03:30
This is a duplicate of #7, I don’t see why this is a separate issue. To quote @nitedog from #7:

> I love the different background for the metadata, like tags and license information. This makes it easy to distinguish from the description and ignore unless interested.
> 
> However, I think they should be more skimable. Currently some entries appear on a line of their own (eg. tags). Others appear inline and look quite crammed to me. It is hard to find the information that I'm looking for. Put each on a line of their own to make the information easier to scan.

**Comment by nitedog** [comment] 2016-05-05 05:37
#7 is putting each line on its own (not sure why this was closed, I don't see it addressed yet). #8 is changing the wording of these lines to further improve skimming. Sorry, I should have been clearer.

**Comment by yatil** [comment] 2016-05-05 10:47
If I change it to be on its own line, I can change the wording at the same time. It is just “change the metadata” for me. ;-)

**Closed as completed** 2016-08-04 11:22 UTC
